version: "3.9"
services:
  front-end:
    container_name: client
    restart: always
    build: ./front-end
    ports: 
      - "3000:3000"
    environment:
      NODE_ENV: production
    links:
      - back-end
  back-end:
    container_name: app
    restart: always
    build: ./back-end
    ports:
      - "5050:5050"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
    ports:
       - "27017:27017"
