version: '3.4'

services:
  capstone_server_1:
    image: capstone_server_1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5051:5051
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
